var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/marketplace/activity/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__abc9e597._.js")
R.c("server/chunks/ssr/f056e_a7b52345._.js")
R.c("server/chunks/ssr/_98e726be._.js")
R.c("server/chunks/ssr/Desktop_kektechbmad100_kektech-mainnet-frontend_app_fe2054f6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28424f5d._.js")
R.c("server/chunks/ssr/f056e_next_dist_client_components_95e675e9._.js")
R.c("server/chunks/ssr/f056e_next_dist_client_components_builtin_forbidden_92342383.js")
R.c("server/chunks/ssr/f056e_next_dist_client_components_builtin_unauthorized_8a265d6b.js")
R.c("server/chunks/ssr/f056e_next_dist_client_components_builtin_global-error_6777cb7c.js")
R.c("server/chunks/ssr/[root-of-the-server]__85ae9f86._.js")
R.c("server/chunks/ssr/Desktop_kektechbmad100_kektech-mainnet-frontend_afccc0fc._.js")
R.c("server/chunks/ssr/Desktop_kektechbmad100_kektech-mainnet-frontend_1dc597a8._.js")
R.m(480800)
R.m(3077)
module.exports=R.m(3077).exports
