// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/buttons-demo" | "/dashboard" | "/feels-good-markets" | "/feels-good-markets/frog-futures" | "/feels-good-markets/kek-futures" | "/feels-good-markets/kek-futures/create" | "/feels-good-markets/kek-futures/market/[id]" | "/feels-good-markets/kek-futures/positions" | "/feels-good-markets/nft-marketplace" | "/feels-good-markets/nft-marketplace/activity" | "/feels-good-markets/nft-marketplace/history/[tokenId]" | "/gallery" | "/marketplace" | "/marketplace/activity" | "/marketplace/history/[tokenId]" | "/markets" | "/markets/[id]" | "/markets/create" | "/mint" | "/nft" | "/positions" | "/rewards" | "/staking"
type AppRouteHandlerRoutes = "/api/comments/[commentId]/vote" | "/api/comments/market/[marketAddress]" | "/api/health" | "/api/marketplace/listings" | "/api/nft/[tokenId]" | "/api/nfts-complete" | "/api/proposals/[marketAddress]/vote" | "/api/rankings" | "/api/resolution/[marketAddress]/vote" | "/api/rpc"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/api/comments/[commentId]/vote": { "commentId": string; }
  "/api/comments/market/[marketAddress]": { "marketAddress": string; }
  "/api/health": {}
  "/api/marketplace/listings": {}
  "/api/nft/[tokenId]": { "tokenId": string; }
  "/api/nfts-complete": {}
  "/api/proposals/[marketAddress]/vote": { "marketAddress": string; }
  "/api/rankings": {}
  "/api/resolution/[marketAddress]/vote": { "marketAddress": string; }
  "/api/rpc": {}
  "/buttons-demo": {}
  "/dashboard": {}
  "/feels-good-markets": {}
  "/feels-good-markets/frog-futures": {}
  "/feels-good-markets/kek-futures": {}
  "/feels-good-markets/kek-futures/create": {}
  "/feels-good-markets/kek-futures/market/[id]": { "id": string; }
  "/feels-good-markets/kek-futures/positions": {}
  "/feels-good-markets/nft-marketplace": {}
  "/feels-good-markets/nft-marketplace/activity": {}
  "/feels-good-markets/nft-marketplace/history/[tokenId]": { "tokenId": string; }
  "/gallery": {}
  "/marketplace": {}
  "/marketplace/activity": {}
  "/marketplace/history/[tokenId]": { "tokenId": string; }
  "/markets": {}
  "/markets/[id]": { "id": string; }
  "/markets/create": {}
  "/mint": {}
  "/nft": {}
  "/positions": {}
  "/rewards": {}
  "/staking": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
