// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/buttons-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buttons-demo">> = Specific
  const handler = {} as typeof import("../../app/buttons-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/frog-futures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/frog-futures">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/frog-futures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/kek-futures/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/kek-futures/create">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/kek-futures/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/kek-futures/market/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/kek-futures/market/[id]">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/kek-futures/market/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/kek-futures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/kek-futures">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/kek-futures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/kek-futures/positions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/kek-futures/positions">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/kek-futures/positions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/nft-marketplace/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/nft-marketplace/activity">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/nft-marketplace/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/nft-marketplace/history/[tokenId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/nft-marketplace/history/[tokenId]">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/nft-marketplace/history/[tokenId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/nft-marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets/nft-marketplace">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/nft-marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feels-good-markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feels-good-markets">> = Specific
  const handler = {} as typeof import("../../app/feels-good-markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../app/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/activity">> = Specific
  const handler = {} as typeof import("../../app/marketplace/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/history/[tokenId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/history/[tokenId]">> = Specific
  const handler = {} as typeof import("../../app/marketplace/history/[tokenId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../app/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/markets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets/[id]">> = Specific
  const handler = {} as typeof import("../../app/markets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/markets/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets/create">> = Specific
  const handler = {} as typeof import("../../app/markets/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets">> = Specific
  const handler = {} as typeof import("../../app/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mint">> = Specific
  const handler = {} as typeof import("../../app/mint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nft">> = Specific
  const handler = {} as typeof import("../../app/nft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/positions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/positions">> = Specific
  const handler = {} as typeof import("../../app/positions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rewards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rewards">> = Specific
  const handler = {} as typeof import("../../app/rewards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staking">> = Specific
  const handler = {} as typeof import("../../app/staking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/comments/[commentId]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[commentId]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/comments/[commentId]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/comments/market/[marketAddress]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/market/[marketAddress]">> = Specific
  const handler = {} as typeof import("../../app/api/comments/market/[marketAddress]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketplace/listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/listings">> = Specific
  const handler = {} as typeof import("../../app/api/marketplace/listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nft/[tokenId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nft/[tokenId]">> = Specific
  const handler = {} as typeof import("../../app/api/nft/[tokenId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nfts-complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nfts-complete">> = Specific
  const handler = {} as typeof import("../../app/api/nfts-complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposals/[marketAddress]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[marketAddress]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/proposals/[marketAddress]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rankings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rankings">> = Specific
  const handler = {} as typeof import("../../app/api/rankings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/resolution/[marketAddress]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resolution/[marketAddress]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/resolution/[marketAddress]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rpc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc">> = Specific
  const handler = {} as typeof import("../../app/api/rpc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
